version: "3.8"

services:
  message:
      image: fmoriguchi/spring-boot-artemis:0.0.2
      container_name: message
      build: .
      ports:
        - "80:8080"
      depends_on:
        - artemis

  artemis:
      image: apache/activemq-artemis:2.31.2
      container_name: artemis
      ports:
          - "61616:61616"
          - "8161:8161"
      expose:
          - "8161"
          - "61616"
      environment:
          - ARTEMIS_USER=admin
          - ARTEMIS_PASSWORD=admin
          #- EXTRA_ARGS= --http-host 0.0.0.0 --relax-jolokia --max-disk-usage=100


